# add the linters you want stickler to use for this project
linters:
  stylelint:
    # indicate where is the config file for stylelint
    config: "stylelint.config.js"

    # Added to avoid errors when using @mixin in the attempt to modularize the SASS code
    config: "customs.config.js"

# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config

# find full documentation here: https://stickler-ci.com/docs
